fix(wl): add missing header for non-glibc after ee5bf816d1f7
como/xwl/socket.cpp:124:9: error: use of undeclared identifier 'close'
        close(fd);
        ^
como/xwl/socket.cpp:129:9: error: use of undeclared identifier 'close'
        close(fd);
        ^
como/xwl/socket.cpp:155:44: error: use of undeclared identifier 'getuid'
    if (info.st_uid != 0 && info.st_uid != getuid()) {
                                           ^
como/xwl/socket.cpp:184:17: error: use of undeclared identifier 'close'
                close(fd);
                ^
como/xwl/socket.cpp:223:9: error: use of undeclared identifier 'close'
        close(fd);
        ^